version: "3"

services:
  campsite-booking-api:
    image: sstjerne.campsite.booking.api/campsite-booking-api
    env_file:
      - sstjerne.campsite.booking.api.database.local.env      
    ports:
      - "8080:8080" 
      - "8001:8001"
    networks:
      - db-network
    entrypoint:
      - java
      - -Xdebug
      - -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=n
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - /app.jar            
  campsite-booking-database:
    image: postgres:9.4.15-alpine
    env_file:
      - sstjerne.campsite.booking.api.database.local.env
    ports:
      - "5432:5432"
    networks:
      - db-network
networks:
  db-network: